# Generated by Django 4.1.4 on 2023-01-12 21:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(blank=True, default=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking')),
            ],
            options={
                'verbose_name': 'Parking spot',
                'verbose_name_plural': 'Parking spots',
            },
        ),
        migrations.CreateModel(
            name='SpotReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_spot', models.TextField(default=None, null=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_number_of_spots', models.IntegerField()),
                ('start_rental_day', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_rental_day', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('rental_days', models.IntegerField(blank=True, null=True)),
                ('reservation_status', models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Not confirmed', 'Not confirmed')], help_text='Reservation status', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['end_rental_day'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpotInstance',
            fields=[
                ('spot_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular spot across whole parking', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Spot availability', max_length=1)),
                ('parking_spot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingspot')),
            ],
        ),
    ]
