# Generated by Django 4.1.4 on 2023-01-10 22:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_number_of_items', models.IntegerField()),
                ('product_items', models.JSONField()),
                ('start_rental_day', models.DateField(default=datetime.date.today)),
                ('end_rental_day', models.DateField(default=datetime.date.today)),
                ('total_rental_days', models.IntegerField()),
                ('rental_status', models.CharField(choices=[('Booked', 'Booked'), ('Not confirmed', 'Not confirmed')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
