# Generated by Django 4.1.4 on 2023-01-11 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_rental_day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rental_status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Not confirmed', 'Not confirmed')], help_text='Order status', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_rental_day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_rental_days',
            field=models.IntegerField(max_length=3),
        ),
    ]
