# Generated by Django 4.1.4 on 2023-01-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_order_end_rental_day_alter_order_rental_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_rental_days',
            field=models.IntegerField(),
        ),
    ]
